spring:
  application:
      name: logisticsApi
  datasource:
    url: jdbc:postgresql://localhost:5432/live_easydb
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
